version: "3"
services:

  moviemongo:
    container_name: moviemongo
    image: mongo:3.6
    ports:
       - 27017:27017

  moviegres:
     container_name: moviegres
     image: qquest/qquest_testautomation_workshop_moviegres:v1
     ports:
       - 5434:5432
     environment:
       - POSTGRES_PASSWORD=test
       - POSTGRES_USER=postgres

  users:
    image: qquest/qquest_testautomation_workshop_users:v1
    ports:
      - 4242:4242
    depends_on:
      - moviegres
    links:
      - moviegres
    environment:
      - ASPNETCORE_ENVIRONMENT="Development"

  movies:
    image: qquest/qquest_testautomation_workshop_movies:v1
    ports:
       - 4243:4243  # expose ports - HOST:CONTAINER
    depends_on:
       - moviemongo
    links:
       - moviemongo
    environment:
       - APP_SETTINGS=production
       - MONGO_URL=mongodb://moviemongo:27017

  proxy:
    image: qquest/qquest_testautomation_workshop_proxy:v1
    ports:
      - 4241:8080
    depends_on:
       - movies
       - users
    links:
       - movies
       - users
    environment:
       - APP_SETTINGS=Production

  dataseeder:
    image: qquest/qquest_testautomation_workshop_dataseeder:v1
    depends_on:
       - moviemongo
       - moviegres
       - users
    links:
       - moviemongo
       - moviegres
       - users