version: "3"
services:

  moviemongo:
    container_name: moviemongo
    image: mongo:3.6
    ports:
       - 27017:27017

  moviegres:
     container_name: moviegres
     build: ./data_seeder/db
     image: joerivrij/testautomation_workshop_moviegres:v3
     ports:
       - 5434:5432
     environment:
       - POSTGRES_PASSWORD=test
       - POSTGRES_USER=postgres

  users:
    image: joerivrij/testautomation_workshop_users:v3
    build: ./v3/backend_users/backend_users
    ports:
      - 4242:4242
    depends_on:
      - moviegres
    links:
      - moviegres
    environment:
      - ASPNETCORE_ENVIRONMENT="Development"

  movies:
    image: joerivrij/testautomation_workshop_movies:v3
    build: ./v3/backend_movies
    ports:
       - 4243:4243  # expose ports - HOST:CONTAINER
    depends_on:
       - moviemongo
    links:
       - moviemongo
    environment:
       - APP_SETTINGS=production
       - MONGO_URL=mongodb://moviemongo:27017

  proxy:
    image: joerivrij/testautomation_workshop_proxy:v3
    build: ./v3/backend_proxy
    ports:
      - 8080:8080
    depends_on:
       - movies
       - users
    links:
       - movies
       - users
    environment:
       - APP_SETTINGS=Production

  dataseeder:
    build: ./data_seeder
    image: joerivrij/testautomation_workshop_dataseeder:v3
    depends_on:
       - moviemongo
       - moviegres
       - users
    links:
       - moviemongo
       - moviegres
       - users
